# Placeholder & Model management_Handson

## 1. Placeholder

For using mini-batch gradient descent, we have to change X, y at every iteration. To avoid this, we can use placeholder.

This node doesn't calculate anything and exists just for delivering data to train.

After making placeholder to deliver data, feed data by feed_dict method.

In [1]:
import tensorflow as tf
import numpy as np

A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A:[[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A:[[4, 5, 6], [7, 8, 9]]})
    
print(B_val_1)
print(B_val_2)

C:\Anaconda_\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[[6. 7. 8.]]
[[ 9. 10. 11.]
 [12. 13. 14.]]


##### In mini-batch

To realize mini-batch gradient descent first, define X, y as place holder and then batch size and batch number.

In [2]:
'''
X = tf.placeholder(tf.float32, shape=(None, n + 1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")

batch_size = 100
n_batches = int(np.ceil(m / batch_size))
'''

'\nX = tf.placeholder(tf.float32, shape=(None, n + 1), name="X")\ny = tf.placeholder(tf.float32, shape=(None, 1), name="y")\n\nbatch_size = 100\nn_batches = int(np.ceil(m / batch_size))\n'

In this code m means number of samples and shape means data size of input and output.

#### How to realize

In [3]:
'''
def fetch_batch(epoch, batch_index, batch_size):
    [...] # data load
    return X_batch, y_batch

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = fetch_batch(epoch, batch_index, batch_size)
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
            
    best_theta = theta.eval()
'''

'\ndef fetch_batch(epoch, batch_index, batch_size):\n    [...] # data load\n    return X_batch, y_batch\n\nwith tf.Session() as sess:\n    sess.run(init)\n    \n    for epoch in range(n_epochs):\n        for batch_index in range(n_batches):\n            X_batch, y_batch = fetch_batch(epoch, batch_index, batch_size)\n            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})\n            \n    best_theta = theta.eval()\n'

## 2. Model Management

### 2.1 Save

After training model, parameters have to be saved to reuse. Or during training, we can make 'checkpoint' by saving model.

It is easy to save in tensor flow.

At last, add Saver node and when you want to save model during execution, call save() method delivering route.

In [4]:
'''
[...]
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name = 'theta')
[...]
init = tf.global_variables_initializer()
saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            save_path = saver.save(sess, "/tmp/my_model.ckpt")
            
        sess.run(training_op)
    
    best_theta = theta.eval()
    save_path = saver.save(sess, "/tmp/mymodel_final.ckpt")
'''

'\n[...]\ntheta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name = \'theta\')\n[...]\ninit = tf.global_variables_initializer()\nsaver = tf.train.Saver()\n\nwith tf.Session() as sess:\n    sess.run(init)\n    \n    for epoch in range(n_epochs):\n        if epoch % 100 == 0:\n            save_path = saver.save(sess, "/tmp/my_model.ckpt")\n            \n        sess.run(training_op)\n    \n    best_theta = theta.eval()\n    save_path = saver.save(sess, "/tmp/mymodel_final.ckpt")\n'

### 2.2 Restore

As save operated, it has same process. Add Saver node and call restore() method.

In [5]:
'''
with tf.Session() as sess:
    saver.restore(sess, "/tmp/my_model_final.ckpt")
    [...]
'''

'\nwith tf.Session() as sess:\n    saver.restore(sess, "/tmp/my_model_final.ckpt")\n    [...]\n'

Saver, at base, saves and restores all variables. And we can name to those as another name.

In [6]:
# saver = tf.train.Saver({"weights": theta})